# Generated by Django 5.0.9 on 2025-04-13 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0191_module_bay_rebuild'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cable_length', models.PositiveIntegerField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('cable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='dcim.cable')),
            ],
        ),
    ]
